name: flutter_google_places_autocomplete
description: Google places autocomplete widgets for flutter
version: 1.0.0
repository: https://github.com/fluttercommunity/flutter_google_places_autocomplete
homepage: https://github.com/dev-juju/flutter_google_places_autocomplete

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter_google_maps_webservices: ^1.0.0
  google_api_headers: ^2.0.0
  http: ^1.0.0
  rxdart: ^0.27.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^2.1.2

flutter:
  assets:
    - packages/flutter_google_places_autocomplete/assets/google_black.png
    - packages/flutter_google_places_autocomplete/assets/google_white.png
